/* The following code was generated by JFlex 1.6.1 */

import java_cup.runtime.*;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>../src/flex/lcalc.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\10\1\11\1\1\22\0\1\66\1\46\1\6"+
    "\2\0\1\62\1\64\1\42\1\51\1\52\1\61\1\57\1\50\1\60"+
    "\1\36\1\63\12\4\1\0\1\47\1\44\1\43\1\45\2\0\32\5"+
    "\1\53\1\7\1\54\1\0\1\5\1\0\1\14\1\33\1\12\1\22"+
    "\1\16\1\35\1\31\1\37\1\23\1\5\1\30\1\13\1\24\1\21"+
    "\1\26\1\25\1\5\1\27\1\15\1\20\1\32\1\34\1\40\1\17"+
    "\1\41\1\5\1\55\1\65\1\56\7\0\1\10\u1fa2\0\1\10\1\10"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\14\4\1\6"+
    "\1\4\1\7\1\1\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\0\1\32\1\0"+
    "\14\4\1\33\2\4\1\34\12\4\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\13\4\1\43\2\4\1\44\12\4"+
    "\1\45\2\4\1\46\3\4\1\47\1\4\1\50\1\51"+
    "\1\52\1\4\1\53\11\4\1\54\1\55\3\4\1\56"+
    "\2\4\1\57\7\4\1\60\3\4\1\61\1\62\1\63"+
    "\1\4\1\64\1\4\1\65\3\4\1\66\2\4\1\67"+
    "\2\4\1\70\3\4\1\71\1\4\1\72\1\73\5\4"+
    "\1\74\1\4\1\75\1\4\1\76\1\77";

  private static int [] zzUnpackAction() {
    int [] result = new int[179];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\67\0\245\0\334\0\u0113\0\u014a"+
    "\0\u0181\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302"+
    "\0\u0339\0\u0370\0\u03a7\0\67\0\u03de\0\67\0\u0415\0\u044c"+
    "\0\u0483\0\u04ba\0\67\0\67\0\67\0\67\0\67\0\67"+
    "\0\67\0\67\0\67\0\67\0\67\0\67\0\67\0\u04f1"+
    "\0\u0528\0\u0113\0\67\0\u055f\0\u0596\0\u05cd\0\u0604\0\u063b"+
    "\0\u0672\0\u06a9\0\u06e0\0\u0717\0\u074e\0\u0785\0\u07bc\0\u07f3"+
    "\0\334\0\u082a\0\u0861\0\334\0\u0898\0\u08cf\0\u0906\0\u093d"+
    "\0\u0974\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87\0\67\0\67"+
    "\0\67\0\67\0\67\0\67\0\u0abe\0\u0af5\0\u0b2c\0\u0b63"+
    "\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f\0\u0c76\0\u0cad\0\u0ce4\0\334"+
    "\0\u0d1b\0\u0d52\0\u0d89\0\u0dc0\0\u0df7\0\u0e2e\0\u0e65\0\u0e9c"+
    "\0\u0ed3\0\u0f0a\0\u0f41\0\u0f78\0\u0faf\0\334\0\u0fe6\0\u101d"+
    "\0\334\0\u1054\0\u108b\0\u10c2\0\334\0\u10f9\0\334\0\334"+
    "\0\334\0\u1130\0\334\0\u1167\0\u119e\0\u11d5\0\u120c\0\u1243"+
    "\0\u127a\0\u12b1\0\u12e8\0\u131f\0\334\0\334\0\u1356\0\u138d"+
    "\0\u13c4\0\334\0\u13fb\0\u1432\0\334\0\u1469\0\u14a0\0\u14d7"+
    "\0\u150e\0\u1545\0\u157c\0\u15b3\0\334\0\u15ea\0\u1621\0\u1658"+
    "\0\334\0\334\0\334\0\u168f\0\334\0\u16c6\0\334\0\u16fd"+
    "\0\u1734\0\u176b\0\334\0\u17a2\0\u17d9\0\334\0\u1810\0\u1847"+
    "\0\334\0\u187e\0\u18b5\0\u18ec\0\334\0\u1923\0\334\0\334"+
    "\0\u195a\0\u1991\0\u19c8\0\u19ff\0\u1a36\0\334\0\u1a6d\0\334"+
    "\0\u1aa4\0\334\0\67";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[179];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\2\2\1\4"+
    "\1\10\1\6\1\11\1\12\1\13\1\6\1\14\1\15"+
    "\1\16\1\17\1\6\1\20\5\6\1\21\1\22\1\23"+
    "\1\24\1\6\1\25\1\6\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\4\71\0\1\4\70\0\1\5\66\0\2\6\4\0"+
    "\24\6\1\0\3\6\25\0\6\52\1\53\1\54\57\52"+
    "\4\0\2\6\4\0\1\6\1\55\22\6\1\0\1\56"+
    "\2\6\31\0\2\6\4\0\21\6\1\57\2\6\1\0"+
    "\3\6\31\0\2\6\4\0\6\6\1\60\15\6\1\0"+
    "\1\61\2\6\31\0\2\6\4\0\1\6\1\62\3\6"+
    "\1\63\16\6\1\0\3\6\31\0\2\6\4\0\15\6"+
    "\1\64\6\6\1\0\1\65\2\6\31\0\2\6\4\0"+
    "\2\6\1\66\1\6\1\67\13\6\1\70\3\6\1\0"+
    "\3\6\31\0\2\6\4\0\14\6\1\71\7\6\1\0"+
    "\3\6\31\0\2\6\4\0\7\6\1\72\2\6\1\73"+
    "\10\6\1\74\1\0\3\6\31\0\2\6\4\0\2\6"+
    "\1\75\12\6\1\76\2\6\1\77\3\6\1\0\3\6"+
    "\31\0\2\6\4\0\14\6\1\100\7\6\1\0\2\6"+
    "\1\101\31\0\2\6\4\0\14\6\1\102\7\6\1\0"+
    "\3\6\31\0\2\6\4\0\2\6\1\103\6\6\1\104"+
    "\2\6\1\105\7\6\1\0\3\6\31\0\2\6\4\0"+
    "\24\6\1\0\1\106\2\6\70\0\1\107\66\0\1\110"+
    "\66\0\1\111\66\0\1\112\107\0\1\113\67\0\1\114"+
    "\1\0\1\52\2\0\5\52\2\0\55\52\4\0\2\6"+
    "\4\0\2\6\1\115\21\6\1\0\3\6\31\0\2\6"+
    "\4\0\2\6\1\116\21\6\1\0\3\6\31\0\2\6"+
    "\4\0\3\6\1\117\20\6\1\0\3\6\31\0\2\6"+
    "\4\0\2\6\1\120\21\6\1\0\3\6\31\0\2\6"+
    "\4\0\14\6\1\121\7\6\1\0\3\6\31\0\2\6"+
    "\4\0\3\6\1\122\20\6\1\0\3\6\31\0\2\6"+
    "\4\0\6\6\1\123\15\6\1\0\3\6\31\0\2\6"+
    "\4\0\20\6\1\124\3\6\1\0\3\6\31\0\2\6"+
    "\4\0\4\6\1\125\4\6\1\126\12\6\1\0\3\6"+
    "\31\0\2\6\4\0\6\6\1\127\15\6\1\0\3\6"+
    "\31\0\2\6\4\0\24\6\1\0\1\6\1\130\1\6"+
    "\31\0\2\6\4\0\1\6\1\131\22\6\1\0\3\6"+
    "\31\0\2\6\4\0\3\6\1\132\2\6\1\133\15\6"+
    "\1\0\3\6\31\0\2\6\4\0\13\6\1\134\10\6"+
    "\1\0\3\6\31\0\2\6\4\0\1\135\23\6\1\0"+
    "\3\6\31\0\2\6\4\0\11\6\1\136\2\6\1\137"+
    "\7\6\1\0\3\6\31\0\2\6\4\0\21\6\1\140"+
    "\2\6\1\0\3\6\31\0\2\6\4\0\14\6\1\141"+
    "\7\6\1\0\3\6\31\0\2\6\4\0\6\6\1\142"+
    "\15\6\1\0\3\6\31\0\2\6\4\0\11\6\1\143"+
    "\12\6\1\0\3\6\31\0\2\6\4\0\1\6\1\144"+
    "\22\6\1\0\3\6\31\0\2\6\4\0\7\6\1\145"+
    "\14\6\1\0\3\6\31\0\2\6\4\0\15\6\1\146"+
    "\6\6\1\0\3\6\31\0\2\6\4\0\11\6\1\147"+
    "\12\6\1\0\3\6\31\0\2\6\4\0\3\6\1\150"+
    "\20\6\1\0\3\6\31\0\2\6\4\0\15\6\1\151"+
    "\6\6\1\0\3\6\31\0\2\6\4\0\6\6\1\152"+
    "\15\6\1\0\3\6\31\0\2\6\4\0\6\6\1\153"+
    "\15\6\1\0\3\6\31\0\2\6\4\0\15\6\1\154"+
    "\6\6\1\0\3\6\31\0\2\6\4\0\4\6\1\155"+
    "\17\6\1\0\3\6\31\0\2\6\4\0\4\6\1\156"+
    "\17\6\1\0\3\6\31\0\2\6\4\0\4\6\1\157"+
    "\17\6\1\0\3\6\31\0\2\6\4\0\7\6\1\160"+
    "\14\6\1\0\3\6\31\0\2\6\4\0\3\6\1\161"+
    "\20\6\1\0\3\6\31\0\2\6\4\0\11\6\1\162"+
    "\12\6\1\0\3\6\31\0\2\6\4\0\1\6\1\163"+
    "\22\6\1\0\3\6\31\0\2\6\4\0\6\6\1\164"+
    "\15\6\1\0\3\6\31\0\2\6\4\0\4\6\1\165"+
    "\17\6\1\0\3\6\31\0\2\6\4\0\1\6\1\166"+
    "\12\6\1\167\7\6\1\0\3\6\31\0\2\6\4\0"+
    "\16\6\1\170\5\6\1\0\3\6\31\0\2\6\4\0"+
    "\7\6\1\171\14\6\1\0\3\6\31\0\2\6\4\0"+
    "\6\6\1\172\15\6\1\0\3\6\31\0\2\6\4\0"+
    "\1\6\1\173\22\6\1\0\3\6\31\0\2\6\4\0"+
    "\1\6\1\174\22\6\1\0\3\6\31\0\2\6\4\0"+
    "\4\6\1\175\17\6\1\0\3\6\31\0\2\6\4\0"+
    "\10\6\1\176\13\6\1\0\3\6\31\0\2\6\4\0"+
    "\3\6\1\177\20\6\1\0\3\6\31\0\2\6\4\0"+
    "\2\6\1\200\21\6\1\0\3\6\31\0\2\6\4\0"+
    "\1\6\1\201\22\6\1\0\3\6\31\0\2\6\4\0"+
    "\3\6\1\202\20\6\1\0\3\6\31\0\2\6\4\0"+
    "\15\6\1\203\6\6\1\0\3\6\31\0\2\6\4\0"+
    "\11\6\1\204\12\6\1\0\3\6\31\0\2\6\4\0"+
    "\6\6\1\205\15\6\1\0\3\6\31\0\2\6\4\0"+
    "\7\6\1\206\14\6\1\0\3\6\31\0\2\6\4\0"+
    "\22\6\1\207\1\6\1\0\3\6\31\0\2\6\4\0"+
    "\2\6\1\210\21\6\1\0\3\6\31\0\2\6\4\0"+
    "\15\6\1\211\6\6\1\0\3\6\31\0\2\6\4\0"+
    "\4\6\1\212\17\6\1\0\3\6\31\0\2\6\4\0"+
    "\15\6\1\213\6\6\1\0\3\6\31\0\2\6\4\0"+
    "\2\6\1\214\21\6\1\0\3\6\31\0\2\6\4\0"+
    "\6\6\1\215\15\6\1\0\3\6\31\0\2\6\4\0"+
    "\4\6\1\216\17\6\1\0\3\6\31\0\2\6\4\0"+
    "\11\6\1\217\12\6\1\0\3\6\31\0\2\6\4\0"+
    "\4\6\1\220\17\6\1\0\3\6\31\0\2\6\4\0"+
    "\4\6\1\221\17\6\1\0\3\6\31\0\2\6\4\0"+
    "\1\6\1\222\22\6\1\0\3\6\31\0\2\6\4\0"+
    "\4\6\1\223\17\6\1\0\3\6\31\0\2\6\4\0"+
    "\2\6\1\224\21\6\1\0\3\6\31\0\2\6\4\0"+
    "\1\225\23\6\1\0\3\6\31\0\2\6\4\0\10\6"+
    "\1\226\13\6\1\0\3\6\31\0\2\6\4\0\4\6"+
    "\1\227\17\6\1\0\3\6\31\0\2\6\4\0\7\6"+
    "\1\230\14\6\1\0\3\6\31\0\2\6\4\0\23\6"+
    "\1\231\1\0\3\6\31\0\2\6\4\0\12\6\1\232"+
    "\11\6\1\0\3\6\31\0\2\6\4\0\6\6\1\233"+
    "\15\6\1\0\3\6\31\0\2\6\4\0\17\6\1\234"+
    "\4\6\1\0\3\6\31\0\2\6\4\0\1\235\23\6"+
    "\1\0\3\6\31\0\2\6\4\0\1\236\23\6\1\0"+
    "\3\6\31\0\2\6\4\0\2\6\1\237\21\6\1\0"+
    "\3\6\31\0\2\6\4\0\1\240\23\6\1\0\3\6"+
    "\31\0\2\6\4\0\3\6\1\241\20\6\1\0\3\6"+
    "\31\0\2\6\4\0\1\242\23\6\1\0\3\6\31\0"+
    "\2\6\4\0\2\6\1\243\21\6\1\0\3\6\31\0"+
    "\2\6\4\0\4\6\1\244\17\6\1\0\3\6\31\0"+
    "\2\6\4\0\4\6\1\245\17\6\1\0\3\6\31\0"+
    "\2\6\4\0\6\6\1\246\15\6\1\0\3\6\31\0"+
    "\2\6\4\0\7\6\1\247\14\6\1\0\3\6\31\0"+
    "\2\6\4\0\6\6\1\250\15\6\1\0\3\6\31\0"+
    "\2\6\4\0\4\6\1\251\17\6\1\0\3\6\31\0"+
    "\2\6\4\0\1\252\23\6\1\0\3\6\31\0\2\6"+
    "\4\0\7\6\1\253\14\6\1\0\3\6\31\0\2\6"+
    "\4\0\4\6\1\254\17\6\1\0\3\6\31\0\2\6"+
    "\4\0\14\6\1\255\7\6\1\0\3\6\31\0\2\6"+
    "\4\0\4\6\1\256\17\6\1\0\3\6\31\0\2\6"+
    "\4\0\6\6\1\257\15\6\1\0\3\6\31\0\2\6"+
    "\4\0\10\6\1\260\13\6\1\0\3\6\31\0\2\6"+
    "\4\0\23\6\1\261\1\0\3\6\31\0\2\6\4\0"+
    "\3\6\1\262\20\6\1\0\3\6\31\0\2\6\4\0"+
    "\24\6\1\0\3\6\24\0\1\263";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6875];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\17\1\1\11\1\1\1\11"+
    "\4\1\15\11\2\1\1\0\1\11\1\0\32\1\6\11"+
    "\146\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[179];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 174) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case YYINITIAL: {
              return symbol(sym.EOF);
            }
            case 180: break;
            default:
          { return new java_cup.runtime.Symbol(sym.EOF); }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Illegal character <"+yytext()+">");
            }
          case 64: break;
          case 2: 
            { /* do nothing */
            }
          case 65: break;
          case 3: 
            { return symbol(sym.INTGERLITERAL, new Integer(yytext()));
            }
          case 66: break;
          case 4: 
            { return symbol(sym.IDENT, new String(yytext()));
            }
          case 67: break;
          case 5: 
            { return symbol(sym.DOUBLEQUOTE);
            }
          case 68: break;
          case 6: 
            { return symbol(sym.DOT);
            }
          case 69: break;
          case 7: 
            { return symbol(sym.SINGLEQUOTE);
            }
          case 70: break;
          case 8: 
            { return symbol(sym.LT);
            }
          case 71: break;
          case 9: 
            { return symbol(sym.GT);
            }
          case 72: break;
          case 10: 
            { return symbol(sym.NOT);
            }
          case 73: break;
          case 11: 
            { return symbol(sym.SEMICOLUMN);
            }
          case 74: break;
          case 12: 
            { return symbol(sym.COMMA);
            }
          case 75: break;
          case 13: 
            { return symbol(sym.LEFTPARN);
            }
          case 76: break;
          case 14: 
            { return symbol(sym.RIGHTPARN);
            }
          case 77: break;
          case 15: 
            { return symbol(sym.LEFTBRACKET);
            }
          case 78: break;
          case 16: 
            { return symbol(sym.RIGHTBARCKET);
            }
          case 79: break;
          case 17: 
            { return symbol(sym.LEFTCURLY);
            }
          case 80: break;
          case 18: 
            { return symbol(sym.RIGHTCURLY);
            }
          case 81: break;
          case 19: 
            { return symbol(sym.PLUS);
            }
          case 82: break;
          case 20: 
            { return symbol(sym.MINUS);
            }
          case 83: break;
          case 21: 
            { return symbol(sym.STAR);
            }
          case 84: break;
          case 22: 
            { return symbol(sym.MOD);
            }
          case 85: break;
          case 23: 
            { return symbol(sym.DIVIDES);
            }
          case 86: break;
          case 24: 
            { return symbol(sym.BITWISEAND);
            }
          case 87: break;
          case 25: 
            { return symbol(sym.BITWISEOR);
            }
          case 88: break;
          case 26: 
            { return symbol(sym.STRING, new String(yytext()));
            }
          case 89: break;
          case 27: 
            { return symbol(sym.DO);
            }
          case 90: break;
          case 28: 
            { return symbol(sym.IF);
            }
          case 91: break;
          case 29: 
            { return symbol(sym.EQ);
            }
          case 92: break;
          case 30: 
            { return symbol(sym.LE);
            }
          case 93: break;
          case 31: 
            { return symbol(sym.GE);
            }
          case 94: break;
          case 32: 
            { return symbol(sym.NE);
            }
          case 95: break;
          case 33: 
            { return symbol(sym.BINARYAND);
            }
          case 96: break;
          case 34: 
            { return symbol(sym.BINARYOR);
            }
          case 97: break;
          case 35: 
            { return symbol(sym.NEW);
            }
          case 98: break;
          case 36: 
            { return symbol(sym.INT);
            }
          case 99: break;
          case 37: 
            { return symbol(sym.FOR);
            }
          case 100: break;
          case 38: 
            { return symbol(sym.CHAR);
            }
          case 101: break;
          case 39: 
            { return symbol(sym.ELSE);
            }
          case 102: break;
          case 40: 
            { return symbol(sym.TRUE);
            }
          case 103: break;
          case 41: 
            { return symbol(sym.THEN);
            }
          case 104: break;
          case 42: 
            { return symbol(sym.ThisLiteral);
            }
          case 105: break;
          case 43: 
            { return symbol(sym.NULLLITERAL);
            }
          case 106: break;
          case 44: 
            { return symbol(sym.BYTE);
            }
          case 107: break;
          case 45: 
            { return symbol(sym.VOID);
            }
          case 108: break;
          case 46: 
            { return symbol(sym.CLASS);
            }
          case 109: break;
          case 47: 
            { return symbol(sym.SHORT);
            }
          case 110: break;
          case 48: 
            { return symbol(sym.PRINT);
            }
          case 111: break;
          case 49: 
            { return symbol(sym.FALSE);
            }
          case 112: break;
          case 50: 
            { return symbol(sym.FINAL);
            }
          case 113: break;
          case 51: 
            { return symbol(sym.WHILE);
            }
          case 114: break;
          case 52: 
            { return symbol(sym.STATIC);
            }
          case 115: break;
          case 53: 
            { return symbol(sym.NATIVE);
            }
          case 116: break;
          case 54: 
            { return symbol(sym.IMPORT);
            }
          case 117: break;
          case 55: 
            { return symbol(sym.PUBLIC);
            }
          case 118: break;
          case 56: 
            { return symbol(sym.EXTENDS);
            }
          case 119: break;
          case 57: 
            { return symbol(sym.PACKAGE);
            }
          case 120: break;
          case 58: 
            { return symbol(sym.BOOL);
            }
          case 121: break;
          case 59: 
            { return symbol(sym.ABSTRACT);
            }
          case 122: break;
          case 60: 
            { return symbol(sym.INTERFACE);
            }
          case 123: break;
          case 61: 
            { return symbol(sym.PROTECTED);
            }
          case 124: break;
          case 62: 
            { return symbol(sym.implements);
            }
          case 125: break;
          case 63: 
            { return symbol(sym.INSTANCEOF);
            }
          case 126: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
