/* The following code was generated by JFlex 1.6.1 */

import java_cup.runtime.*;





/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>./src/flex/joos.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\11\1\12\1\1\22\0\1\3\1\51\1\7"+
    "\2\0\1\64\1\65\1\13\1\54\1\55\1\15\1\62\1\53\1\63"+
    "\1\42\1\14\1\5\11\4\1\0\1\52\1\47\1\46\1\50\2\0"+
    "\32\6\1\56\1\10\1\57\1\0\1\6\1\0\1\20\1\37\1\16"+
    "\1\26\1\22\1\41\1\35\1\44\1\27\1\6\1\34\1\17\1\30"+
    "\1\25\1\32\1\31\1\6\1\33\1\21\1\24\1\36\1\40\1\43"+
    "\1\23\1\45\1\6\1\60\1\66\1\61\7\0\1\11\u1fa2\0\1\11"+
    "\1\11\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\2\3\1\4\2\1\1\5\1\6"+
    "\14\4\1\7\1\4\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\0\1\31\2\0\1\2"+
    "\1\0\16\4\1\32\13\4\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\0\12\4\1\42\2\4\1\43"+
    "\12\4\1\44\1\4\1\2\1\4\1\45\3\4\1\46"+
    "\1\4\1\47\1\50\1\4\1\51\11\4\1\52\1\53"+
    "\3\4\1\54\2\4\1\55\13\4\1\56\1\57\1\60"+
    "\1\4\1\61\1\4\1\62\3\4\1\63\2\4\1\64"+
    "\1\65\2\4\1\66\3\4\1\67\1\4\1\70\1\71"+
    "\5\4\1\72\1\4\1\73\1\74\1\75";

  private static int [] zzUnpackAction() {
    int [] result = new int[184];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\67\0\245\0\67\0\334\0\u0113"+
    "\0\u014a\0\u0181\0\67\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294"+
    "\0\u02cb\0\u0302\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415\0\67"+
    "\0\u044c\0\u0483\0\u04ba\0\u04f1\0\u0528\0\67\0\67\0\67"+
    "\0\67\0\67\0\67\0\67\0\67\0\67\0\67\0\67"+
    "\0\u055f\0\u0596\0\u0113\0\67\0\u05cd\0\u0604\0\u063b\0\u0672"+
    "\0\u06a9\0\u06e0\0\u0717\0\u074e\0\u0785\0\u07bc\0\u07f3\0\u082a"+
    "\0\u0861\0\u0898\0\u08cf\0\u0906\0\u093d\0\u0974\0\334\0\u09ab"+
    "\0\u09e2\0\u0a19\0\u0a50\0\u0a87\0\u0abe\0\u0af5\0\u0b2c\0\u0b63"+
    "\0\u0b9a\0\u0bd1\0\67\0\67\0\67\0\67\0\67\0\67"+
    "\0\67\0\u0c08\0\u0c3f\0\u0c76\0\u0cad\0\u0ce4\0\u0d1b\0\u0d52"+
    "\0\u0d89\0\u0dc0\0\u0df7\0\u0e2e\0\334\0\u0e65\0\u0e9c\0\u0ed3"+
    "\0\u0f0a\0\u0f41\0\u0f78\0\u0faf\0\u0fe6\0\u101d\0\u1054\0\u108b"+
    "\0\u10c2\0\u10f9\0\334\0\u1130\0\u0672\0\u1167\0\334\0\u119e"+
    "\0\u11d5\0\u120c\0\334\0\u1243\0\334\0\334\0\u127a\0\334"+
    "\0\u12b1\0\u12e8\0\u131f\0\u1356\0\u138d\0\u13c4\0\u13fb\0\u1432"+
    "\0\u1469\0\334\0\334\0\u14a0\0\u14d7\0\u150e\0\334\0\u1545"+
    "\0\u157c\0\334\0\u15b3\0\u15ea\0\u1621\0\u1658\0\u168f\0\u16c6"+
    "\0\u16fd\0\u1734\0\u176b\0\u17a2\0\u17d9\0\334\0\334\0\334"+
    "\0\u1810\0\334\0\u1847\0\334\0\u187e\0\u18b5\0\u18ec\0\334"+
    "\0\u1923\0\u195a\0\334\0\334\0\u1991\0\u19c8\0\334\0\u19ff"+
    "\0\u1a36\0\u1a6d\0\334\0\u1aa4\0\334\0\334\0\u1adb\0\u1b12"+
    "\0\u1b49\0\u1b80\0\u1bb7\0\334\0\u1bee\0\334\0\334\0\334";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[184];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\2\2"+
    "\1\4\1\11\1\12\1\13\1\14\1\7\1\15\1\16"+
    "\1\17\1\7\1\20\1\21\1\7\1\22\1\7\1\23"+
    "\1\7\1\24\3\7\1\25\1\26\1\27\1\30\1\31"+
    "\2\7\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\71\0\1\4\70\0\2\5\65\0\3\7"+
    "\7\0\24\7\1\0\3\7\21\0\7\53\1\54\1\55"+
    "\56\53\1\56\2\0\6\56\2\0\54\56\14\0\1\57"+
    "\1\60\55\0\3\7\7\0\1\7\1\61\22\7\1\0"+
    "\1\7\1\62\1\7\25\0\3\7\7\0\21\7\1\63"+
    "\2\7\1\0\3\7\25\0\3\7\7\0\6\7\1\64"+
    "\15\7\1\0\1\7\1\65\1\7\25\0\3\7\7\0"+
    "\1\7\1\66\3\7\1\67\16\7\1\0\3\7\25\0"+
    "\3\7\7\0\15\7\1\70\6\7\1\0\1\7\1\71"+
    "\1\7\25\0\3\7\7\0\2\7\1\72\1\7\1\73"+
    "\13\7\1\74\3\7\1\0\3\7\25\0\3\7\7\0"+
    "\7\7\1\75\2\7\1\76\10\7\1\77\1\0\3\7"+
    "\25\0\3\7\7\0\2\7\1\100\12\7\1\101\2\7"+
    "\1\102\3\7\1\0\3\7\25\0\3\7\7\0\4\7"+
    "\1\103\17\7\1\0\3\7\25\0\3\7\7\0\14\7"+
    "\1\104\7\7\1\0\2\7\1\105\25\0\3\7\7\0"+
    "\14\7\1\106\7\7\1\0\3\7\25\0\3\7\7\0"+
    "\2\7\1\107\6\7\1\110\2\7\1\111\7\7\1\0"+
    "\3\7\25\0\3\7\7\0\24\7\1\0\1\7\1\112"+
    "\1\7\67\0\1\113\66\0\1\114\66\0\1\115\66\0"+
    "\1\116\105\0\1\117\67\0\1\120\1\53\2\0\6\53"+
    "\2\0\54\53\13\0\1\121\53\0\1\57\2\0\6\57"+
    "\2\0\54\57\15\60\1\122\51\60\4\0\3\7\7\0"+
    "\2\7\1\123\21\7\1\0\3\7\25\0\3\7\7\0"+
    "\2\7\1\124\21\7\1\0\3\7\25\0\3\7\7\0"+
    "\3\7\1\125\20\7\1\0\3\7\25\0\3\7\7\0"+
    "\2\7\1\126\21\7\1\0\3\7\25\0\3\7\7\0"+
    "\14\7\1\127\7\7\1\0\3\7\25\0\3\7\7\0"+
    "\3\7\1\130\20\7\1\0\3\7\25\0\3\7\7\0"+
    "\6\7\1\131\15\7\1\0\3\7\25\0\3\7\7\0"+
    "\20\7\1\132\3\7\1\0\3\7\25\0\3\7\7\0"+
    "\11\7\1\133\12\7\1\0\3\7\25\0\3\7\7\0"+
    "\6\7\1\134\15\7\1\0\3\7\25\0\3\7\7\0"+
    "\24\7\1\0\1\135\2\7\25\0\3\7\7\0\1\7"+
    "\1\136\22\7\1\0\3\7\25\0\3\7\7\0\3\7"+
    "\1\137\2\7\1\140\15\7\1\0\3\7\25\0\3\7"+
    "\7\0\13\7\1\141\10\7\1\0\3\7\25\0\3\7"+
    "\7\0\1\142\23\7\1\0\3\7\25\0\3\7\7\0"+
    "\14\7\1\143\7\7\1\0\3\7\25\0\3\7\7\0"+
    "\21\7\1\144\2\7\1\0\3\7\25\0\3\7\7\0"+
    "\6\7\1\145\15\7\1\0\3\7\25\0\3\7\7\0"+
    "\14\7\1\146\7\7\1\0\3\7\25\0\3\7\7\0"+
    "\6\7\1\147\15\7\1\0\3\7\25\0\3\7\7\0"+
    "\11\7\1\150\12\7\1\0\3\7\25\0\3\7\7\0"+
    "\1\7\1\151\22\7\1\0\3\7\25\0\3\7\7\0"+
    "\7\7\1\152\14\7\1\0\3\7\25\0\3\7\7\0"+
    "\15\7\1\153\6\7\1\0\3\7\25\0\3\7\7\0"+
    "\11\7\1\154\12\7\1\0\3\7\21\0\14\60\1\155"+
    "\1\122\51\60\4\0\3\7\7\0\3\7\1\156\20\7"+
    "\1\0\3\7\25\0\3\7\7\0\15\7\1\157\6\7"+
    "\1\0\3\7\25\0\3\7\7\0\6\7\1\160\15\7"+
    "\1\0\3\7\25\0\3\7\7\0\6\7\1\161\15\7"+
    "\1\0\3\7\25\0\3\7\7\0\15\7\1\162\6\7"+
    "\1\0\3\7\25\0\3\7\7\0\4\7\1\163\17\7"+
    "\1\0\3\7\25\0\3\7\7\0\4\7\1\164\17\7"+
    "\1\0\3\7\25\0\3\7\7\0\4\7\1\165\17\7"+
    "\1\0\3\7\25\0\3\7\7\0\3\7\1\166\20\7"+
    "\1\0\3\7\25\0\3\7\7\0\11\7\1\167\12\7"+
    "\1\0\3\7\25\0\3\7\7\0\1\7\1\170\22\7"+
    "\1\0\3\7\25\0\3\7\7\0\6\7\1\171\15\7"+
    "\1\0\3\7\25\0\3\7\7\0\4\7\1\172\17\7"+
    "\1\0\3\7\25\0\3\7\7\0\1\7\1\173\12\7"+
    "\1\174\7\7\1\0\3\7\25\0\3\7\7\0\16\7"+
    "\1\175\5\7\1\0\3\7\25\0\3\7\7\0\6\7"+
    "\1\176\15\7\1\0\3\7\25\0\3\7\7\0\1\7"+
    "\1\177\22\7\1\0\3\7\25\0\3\7\7\0\20\7"+
    "\1\200\3\7\1\0\3\7\25\0\3\7\7\0\1\7"+
    "\1\201\22\7\1\0\3\7\25\0\3\7\7\0\4\7"+
    "\1\202\17\7\1\0\3\7\25\0\3\7\7\0\10\7"+
    "\1\203\13\7\1\0\3\7\25\0\3\7\7\0\3\7"+
    "\1\204\20\7\1\0\3\7\25\0\3\7\7\0\2\7"+
    "\1\205\21\7\1\0\3\7\25\0\3\7\7\0\1\7"+
    "\1\206\22\7\1\0\3\7\25\0\3\7\7\0\3\7"+
    "\1\207\20\7\1\0\3\7\25\0\3\7\7\0\15\7"+
    "\1\210\6\7\1\0\3\7\25\0\3\7\7\0\11\7"+
    "\1\211\12\7\1\0\3\7\25\0\3\7\7\0\6\7"+
    "\1\212\15\7\1\0\3\7\25\0\3\7\7\0\7\7"+
    "\1\213\14\7\1\0\3\7\25\0\3\7\7\0\22\7"+
    "\1\214\1\7\1\0\3\7\25\0\3\7\7\0\2\7"+
    "\1\215\21\7\1\0\3\7\25\0\3\7\7\0\15\7"+
    "\1\216\6\7\1\0\3\7\25\0\3\7\7\0\4\7"+
    "\1\217\17\7\1\0\3\7\25\0\3\7\7\0\15\7"+
    "\1\220\6\7\1\0\3\7\25\0\3\7\7\0\2\7"+
    "\1\221\21\7\1\0\3\7\25\0\3\7\7\0\4\7"+
    "\1\222\17\7\1\0\3\7\25\0\3\7\7\0\11\7"+
    "\1\223\12\7\1\0\3\7\25\0\3\7\7\0\15\7"+
    "\1\224\6\7\1\0\3\7\25\0\3\7\7\0\4\7"+
    "\1\225\17\7\1\0\3\7\25\0\3\7\7\0\4\7"+
    "\1\226\17\7\1\0\3\7\25\0\3\7\7\0\1\7"+
    "\1\227\22\7\1\0\3\7\25\0\3\7\7\0\4\7"+
    "\1\230\17\7\1\0\3\7\25\0\3\7\7\0\2\7"+
    "\1\231\21\7\1\0\3\7\25\0\3\7\7\0\1\232"+
    "\23\7\1\0\3\7\25\0\3\7\7\0\10\7\1\233"+
    "\13\7\1\0\3\7\25\0\3\7\7\0\4\7\1\234"+
    "\17\7\1\0\3\7\25\0\3\7\7\0\7\7\1\235"+
    "\14\7\1\0\3\7\25\0\3\7\7\0\23\7\1\236"+
    "\1\0\3\7\25\0\3\7\7\0\12\7\1\237\11\7"+
    "\1\0\3\7\25\0\3\7\7\0\6\7\1\240\15\7"+
    "\1\0\3\7\25\0\3\7\7\0\17\7\1\241\4\7"+
    "\1\0\3\7\25\0\3\7\7\0\1\242\23\7\1\0"+
    "\3\7\25\0\3\7\7\0\1\243\23\7\1\0\3\7"+
    "\25\0\3\7\7\0\7\7\1\244\14\7\1\0\3\7"+
    "\25\0\3\7\7\0\2\7\1\245\21\7\1\0\3\7"+
    "\25\0\3\7\7\0\1\246\23\7\1\0\3\7\25\0"+
    "\3\7\7\0\3\7\1\247\20\7\1\0\3\7\25\0"+
    "\3\7\7\0\1\250\23\7\1\0\3\7\25\0\3\7"+
    "\7\0\2\7\1\251\21\7\1\0\3\7\25\0\3\7"+
    "\7\0\4\7\1\252\17\7\1\0\3\7\25\0\3\7"+
    "\7\0\4\7\1\253\17\7\1\0\3\7\25\0\3\7"+
    "\7\0\6\7\1\254\15\7\1\0\3\7\25\0\3\7"+
    "\7\0\7\7\1\255\14\7\1\0\3\7\25\0\3\7"+
    "\7\0\6\7\1\256\15\7\1\0\3\7\25\0\3\7"+
    "\7\0\4\7\1\257\17\7\1\0\3\7\25\0\3\7"+
    "\7\0\1\260\23\7\1\0\3\7\25\0\3\7\7\0"+
    "\7\7\1\261\14\7\1\0\3\7\25\0\3\7\7\0"+
    "\4\7\1\262\17\7\1\0\3\7\25\0\3\7\7\0"+
    "\14\7\1\263\7\7\1\0\3\7\25\0\3\7\7\0"+
    "\4\7\1\264\17\7\1\0\3\7\25\0\3\7\7\0"+
    "\6\7\1\265\15\7\1\0\3\7\25\0\3\7\7\0"+
    "\10\7\1\266\13\7\1\0\3\7\25\0\3\7\7\0"+
    "\23\7\1\267\1\0\3\7\25\0\3\7\7\0\3\7"+
    "\1\270\20\7\1\0\3\7\21\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7205];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\1\1\1\11\4\1\1\11"+
    "\14\1\1\11\5\1\13\11\2\1\1\0\1\11\2\0"+
    "\1\1\1\0\32\1\7\11\1\0\146\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[184];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn, new Token(type, ""));
    }
    
    private Symbol symbol(int type, Object value) {
        String lexeme = value.toString();
        return new Symbol(type, yyline, yycolumn, new Token(type, lexeme));
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 176) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case YYINITIAL: {
              return symbol(sym.EOF);
            }
            case 185: break;
            default:
          { return new java_cup.runtime.Symbol(sym.EOF); }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Illegal character <"+yytext()+">");
            }
          case 62: break;
          case 2: 
            { /* do nothing */
            }
          case 63: break;
          case 3: 
            { return symbol(sym.INTGERLITERAL, new Integer(yytext()));
            }
          case 64: break;
          case 4: 
            { return symbol(sym.ID, new String(yytext()));
            }
          case 65: break;
          case 5: 
            { return symbol(sym.DIVIDES, "/");
            }
          case 66: break;
          case 6: 
            { return symbol(sym.STAR, "*");
            }
          case 67: break;
          case 7: 
            { return symbol(sym.DOT, ".");
            }
          case 68: break;
          case 8: 
            { return symbol(sym.ASSIGN, "=");
            }
          case 69: break;
          case 9: 
            { return symbol(sym.LT, "<");
            }
          case 70: break;
          case 10: 
            { return symbol(sym.GT, ">");
            }
          case 71: break;
          case 11: 
            { return symbol(sym.NOT, "!");
            }
          case 72: break;
          case 12: 
            { return symbol(sym.SEMICOLUMN, ";");
            }
          case 73: break;
          case 13: 
            { return symbol(sym.COMMA, ",");
            }
          case 74: break;
          case 14: 
            { return symbol(sym.LEFTPARN, "(");
            }
          case 75: break;
          case 15: 
            { return symbol(sym.RIGHTPARN, ")");
            }
          case 76: break;
          case 16: 
            { return symbol(sym.LEFTBRACKET, "[");
            }
          case 77: break;
          case 17: 
            { return symbol(sym.RIGHTBARCKET, "]");
            }
          case 78: break;
          case 18: 
            { return symbol(sym.LEFTCURLY, "{");
            }
          case 79: break;
          case 19: 
            { return symbol(sym.RIGHTCURLY, "}");
            }
          case 80: break;
          case 20: 
            { return symbol(sym.PLUS, "+");
            }
          case 81: break;
          case 21: 
            { return symbol(sym.MINUS, "-");
            }
          case 82: break;
          case 22: 
            { return symbol(sym.MOD, "%");
            }
          case 83: break;
          case 23: 
            { return symbol(sym.BITWISEAND, "&");
            }
          case 84: break;
          case 24: 
            { return symbol(sym.BITWISEOR, "|");
            }
          case 85: break;
          case 25: 
            { return symbol(sym.STRINGLITERAL, new String(yytext()));
            }
          case 86: break;
          case 26: 
            { return symbol(sym.IF, "if");
            }
          case 87: break;
          case 27: 
            { return symbol(sym.EQ, "==");
            }
          case 88: break;
          case 28: 
            { return symbol(sym.LE, "<=");
            }
          case 89: break;
          case 29: 
            { return symbol(sym.GE, ">=");
            }
          case 90: break;
          case 30: 
            { return symbol(sym.NE, "!=");
            }
          case 91: break;
          case 31: 
            { return symbol(sym.BINARYAND, "&&");
            }
          case 92: break;
          case 32: 
            { return symbol(sym.BINARYOR, "||");
            }
          case 93: break;
          case 33: 
            { return symbol(sym.CHARLITERAL, new String(yytext()));
            }
          case 94: break;
          case 34: 
            { return symbol(sym.NEW, "new");
            }
          case 95: break;
          case 35: 
            { return symbol(sym.INT, "int");
            }
          case 96: break;
          case 36: 
            { return symbol(sym.FOR, "for");
            }
          case 97: break;
          case 37: 
            { return symbol(sym.CHAR, "char");
            }
          case 98: break;
          case 38: 
            { return symbol(sym.ELSE, "else");
            }
          case 99: break;
          case 39: 
            { return symbol(sym.TRUELITERAL, "true");
            }
          case 100: break;
          case 40: 
            { return symbol(sym.THISLITERAL, "this");
            }
          case 101: break;
          case 41: 
            { return symbol(sym.NULLLITERAL, "null");
            }
          case 102: break;
          case 42: 
            { return symbol(sym.BYTE, "byte");
            }
          case 103: break;
          case 43: 
            { return symbol(sym.VOID, "void");
            }
          case 104: break;
          case 44: 
            { return symbol(sym.CLASS, "class");
            }
          case 105: break;
          case 45: 
            { return symbol(sym.SHORT, "short");
            }
          case 106: break;
          case 46: 
            { return symbol(sym.FALSELITERAL, "false");
            }
          case 107: break;
          case 47: 
            { return symbol(sym.FINAL, "final");
            }
          case 108: break;
          case 48: 
            { return symbol(sym.WHILE, "while");
            }
          case 109: break;
          case 49: 
            { return symbol(sym.STATIC, "static");
            }
          case 110: break;
          case 50: 
            { return symbol(sym.NATIVE, "native");
            }
          case 111: break;
          case 51: 
            { return symbol(sym.IMPORT, "import");
            }
          case 112: break;
          case 52: 
            { return symbol(sym.PUBLIC, "public");
            }
          case 113: break;
          case 53: 
            { return symbol(sym.RETURN, "return");
            }
          case 114: break;
          case 54: 
            { return symbol(sym.EXTENDS, "extends");
            }
          case 115: break;
          case 55: 
            { return symbol(sym.PACKAGE, "package");
            }
          case 116: break;
          case 56: 
            { return symbol(sym.BOOL, "boolean");
            }
          case 117: break;
          case 57: 
            { return symbol(sym.ABSTRACT, "abstract");
            }
          case 118: break;
          case 58: 
            { return symbol(sym.INTERFACE, "interface");
            }
          case 119: break;
          case 59: 
            { return symbol(sym.PROTECTED, "protected");
            }
          case 120: break;
          case 60: 
            { return symbol(sym.INSTANCEOF, "instanceof");
            }
          case 121: break;
          case 61: 
            { return symbol(sym.IMPLEMENTS, "implements");
            }
          case 122: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
