
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHARLITERAL = 64;
  public static final int LEFTBRACKET = 33;
  public static final int DIVIDES = 17;
  public static final int TRUELITERAL = 7;
  public static final int SHORT = 13;
  public static final int CHAR = 11;
  public static final int GE = 26;
  public static final int INTGERLITERAL = 3;
  public static final int BITWISEAND = 28;
  public static final int PRIVATE = 52;
  public static final int SEMICOLUMN = 39;
  public static final int INTERFACE = 49;
  public static final int INT = 10;
  public static final int FOR = 40;
  public static final int MINUS = 15;
  public static final int STAR = 16;
  public static final int INSTANCEOF = 62;
  public static final int STATIC = 54;
  public static final int NOT = 21;
  public static final int LT = 23;
  public static final int FALSELITERAL = 8;
  public static final int COMMA = 37;
  public static final int BOOL = 9;
  public static final int CLASS = 48;
  public static final int BITWISEOR = 29;
  public static final int PLUS = 14;
  public static final int ASSIGN = 63;
  public static final int SINGLEQUOTE = 60;
  public static final int IF = 42;
  public static final int DOT = 38;
  public static final int ID = 2;
  public static final int LE = 24;
  public static final int ABSTRACT = 50;
  public static final int EOF = 0;
  public static final int RETURN = 44;
  public static final int BINARYOR = 20;
  public static final int SUPER = 57;
  public static final int RIGHTCURLY = 36;
  public static final int NEW = 30;
  public static final int error = 1;
  public static final int MOD = 18;
  public static final int VOID = 59;
  public static final int EQ = 22;
  public static final int LEFTCURLY = 35;
  public static final int BYTE = 12;
  public static final int IMPORT = 47;
  public static final int NATIVE = 45;
  public static final int ELSE = 43;
  public static final int DOUBLEQUOTE = 61;
  public static final int PROTECTED = 53;
  public static final int RIGHTPARN = 32;
  public static final int RIGHTBARCKET = 34;
  public static final int NULLLITERAL = 5;
  public static final int PACKAGE = 46;
  public static final int FINAL = 58;
  public static final int WHILE = 41;
  public static final int PUBLIC = 51;
  public static final int EXTENDS = 55;
  public static final int NE = 27;
  public static final int STRINGLITERAL = 4;
  public static final int THISLITERAL = 6;
  public static final int IMPLEMENTS = 56;
  public static final int GT = 25;
  public static final int BINARYAND = 19;
  public static final int LEFTPARN = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "INTGERLITERAL",
  "STRINGLITERAL",
  "NULLLITERAL",
  "THISLITERAL",
  "TRUELITERAL",
  "FALSELITERAL",
  "BOOL",
  "INT",
  "CHAR",
  "BYTE",
  "SHORT",
  "PLUS",
  "MINUS",
  "STAR",
  "DIVIDES",
  "MOD",
  "BINARYAND",
  "BINARYOR",
  "NOT",
  "EQ",
  "LT",
  "LE",
  "GT",
  "GE",
  "NE",
  "BITWISEAND",
  "BITWISEOR",
  "NEW",
  "LEFTPARN",
  "RIGHTPARN",
  "LEFTBRACKET",
  "RIGHTBARCKET",
  "LEFTCURLY",
  "RIGHTCURLY",
  "COMMA",
  "DOT",
  "SEMICOLUMN",
  "FOR",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "NATIVE",
  "PACKAGE",
  "IMPORT",
  "CLASS",
  "INTERFACE",
  "ABSTRACT",
  "PUBLIC",
  "PRIVATE",
  "PROTECTED",
  "STATIC",
  "EXTENDS",
  "IMPLEMENTS",
  "SUPER",
  "FINAL",
  "VOID",
  "SINGLEQUOTE",
  "DOUBLEQUOTE",
  "INSTANCEOF",
  "ASSIGN",
  "CHARLITERAL"
  };
}

