
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NEW = 33;
  public static final int INSTANCEOF = 34;
  public static final int EXTENDS = 58;
  public static final int LT = 25;
  public static final int RIGHTBARCKET = 38;
  public static final int CLASS = 52;
  public static final int BINARYAND = 21;
  public static final int STATIC = 57;
  public static final int MINUS = 17;
  public static final int INTERFACE = 53;
  public static final int PACKAGE = 50;
  public static final int BYTE = 14;
  public static final int ELSE = 47;
  public static final int ID = 2;
  public static final int IF = 46;
  public static final int LEFTCURLY = 39;
  public static final int DOT = 42;
  public static final int FOR = 44;
  public static final int FINAL = 61;
  public static final int EQ = 24;
  public static final int BINARYOR = 22;
  public static final int STRINGLITERAL = 5;
  public static final int SEMICOLUMN = 43;
  public static final int NOT = 23;
  public static final int BITWISEOR = 31;
  public static final int NE = 29;
  public static final int PUBLIC = 55;
  public static final int VOID = 10;
  public static final int PLUS = 16;
  public static final int NATIVE = 49;
  public static final int CHAR = 13;
  public static final int error = 1;
  public static final int ASSIGN = 32;
  public static final int ABSTRACT = 54;
  public static final int INTGERLITERAL = 3;
  public static final int NULLLITERAL = 6;
  public static final int INT = 12;
  public static final int BITWISEAND = 30;
  public static final int RETURN = 48;
  public static final int IMPORT = 51;
  public static final int THISLITERAL = 7;
  public static final int FALSELITERAL = 9;
  public static final int CHARLITERAL = 4;
  public static final int RIGHTCURLY = 40;
  public static final int PROTECTED = 56;
  public static final int EOF = 0;
  public static final int GE = 28;
  public static final int COMMA = 41;
  public static final int SUPER = 60;
  public static final int MOD = 19;
  public static final int LEFTBRACKET = 37;
  public static final int TRUELITERAL = 8;
  public static final int IMPLEMENTS = 59;
  public static final int LEFTPARN = 35;
  public static final int DIVIDES = 18;
  public static final int GT = 27;
  public static final int SHORT = 15;
  public static final int STAR = 20;
  public static final int RIGHTPARN = 36;
  public static final int BOOL = 11;
  public static final int LE = 26;
  public static final int WHILE = 45;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "INTGERLITERAL",
  "CHARLITERAL",
  "STRINGLITERAL",
  "NULLLITERAL",
  "THISLITERAL",
  "TRUELITERAL",
  "FALSELITERAL",
  "VOID",
  "BOOL",
  "INT",
  "CHAR",
  "BYTE",
  "SHORT",
  "PLUS",
  "MINUS",
  "DIVIDES",
  "MOD",
  "STAR",
  "BINARYAND",
  "BINARYOR",
  "NOT",
  "EQ",
  "LT",
  "LE",
  "GT",
  "GE",
  "NE",
  "BITWISEAND",
  "BITWISEOR",
  "ASSIGN",
  "NEW",
  "INSTANCEOF",
  "LEFTPARN",
  "RIGHTPARN",
  "LEFTBRACKET",
  "RIGHTBARCKET",
  "LEFTCURLY",
  "RIGHTCURLY",
  "COMMA",
  "DOT",
  "SEMICOLUMN",
  "FOR",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "NATIVE",
  "PACKAGE",
  "IMPORT",
  "CLASS",
  "INTERFACE",
  "ABSTRACT",
  "PUBLIC",
  "PROTECTED",
  "STATIC",
  "EXTENDS",
  "IMPLEMENTS",
  "SUPER",
  "FINAL"
  };
}

