
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package lexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int VOLATILE = 36;
  public static final int NEW = 55;
  public static final int INSTANCEOF = 56;
  public static final int EXTENDS = 80;
  public static final int THROW = 31;
  public static final int LT = 47;
  public static final int RIGHTBARCKET = 60;
  public static final int DO = 24;
  public static final int CLASS = 74;
  public static final int FINALLY = 27;
  public static final int BINARYAND = 43;
  public static final int STATIC = 79;
  public static final int MINUS = 39;
  public static final int INTERFACE = 75;
  public static final int CONST = 23;
  public static final int PACKAGE = 72;
  public static final int BYTE = 14;
  public static final int BREAK = 18;
  public static final int ELSE = 69;
  public static final int TRY = 33;
  public static final int ID = 2;
  public static final int IF = 68;
  public static final int SYNCHRONIZED = 30;
  public static final int ENUM = 26;
  public static final int LEFTCURLY = 61;
  public static final int DOT = 64;
  public static final int FOR = 66;
  public static final int FINAL = 83;
  public static final int EQ = 46;
  public static final int BINARYOR = 44;
  public static final int STRINGLITERAL = 5;
  public static final int CASE = 19;
  public static final int SEMICOLUMN = 65;
  public static final int DATE = 37;
  public static final int NOT = 45;
  public static final int BITWISEOR = 53;
  public static final int NE = 51;
  public static final int THROWS = 34;
  public static final int PUBLIC = 77;
  public static final int SWITCH = 35;
  public static final int VOID = 10;
  public static final int TRANSIENT = 32;
  public static final int PLUS = 38;
  public static final int NATIVE = 71;
  public static final int CHAR = 13;
  public static final int error = 1;
  public static final int ASSIGN = 54;
  public static final int STRICTFP = 29;
  public static final int ABSTRACT = 76;
  public static final int INTGERLITERAL = 3;
  public static final int NULLLITERAL = 6;
  public static final int INT = 12;
  public static final int BITWISEAND = 52;
  public static final int RETURN = 70;
  public static final int IMPORT = 73;
  public static final int THISLITERAL = 7;
  public static final int FALSELITERAL = 9;
  public static final int CATCH = 20;
  public static final int CHARLITERAL = 4;
  public static final int DOUBLE = 25;
  public static final int RIGHTCURLY = 62;
  public static final int PROTECTED = 78;
  public static final int EOF = 0;
  public static final int GE = 50;
  public static final int LONG = 28;
  public static final int COMMA = 63;
  public static final int SUPER = 82;
  public static final int MOD = 41;
  public static final int LEFTBRACKET = 59;
  public static final int ASSERT = 17;
  public static final int TRUELITERAL = 8;
  public static final int IMPLEMENTS = 81;
  public static final int LEFTPARN = 57;
  public static final int DIVIDES = 40;
  public static final int GT = 49;
  public static final int SHORT = 15;
  public static final int PRIVATE = 16;
  public static final int CONTINUE = 21;
  public static final int STAR = 42;
  public static final int RIGHTPARN = 58;
  public static final int BOOL = 11;
  public static final int LE = 48;
  public static final int WHILE = 67;
  public static final int DEFAULT = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "INTGERLITERAL",
  "CHARLITERAL",
  "STRINGLITERAL",
  "NULLLITERAL",
  "THISLITERAL",
  "TRUELITERAL",
  "FALSELITERAL",
  "VOID",
  "BOOL",
  "INT",
  "CHAR",
  "BYTE",
  "SHORT",
  "PRIVATE",
  "ASSERT",
  "BREAK",
  "CASE",
  "CATCH",
  "CONTINUE",
  "DEFAULT",
  "CONST",
  "DO",
  "DOUBLE",
  "ENUM",
  "FINALLY",
  "LONG",
  "STRICTFP",
  "SYNCHRONIZED",
  "THROW",
  "TRANSIENT",
  "TRY",
  "THROWS",
  "SWITCH",
  "VOLATILE",
  "DATE",
  "PLUS",
  "MINUS",
  "DIVIDES",
  "MOD",
  "STAR",
  "BINARYAND",
  "BINARYOR",
  "NOT",
  "EQ",
  "LT",
  "LE",
  "GT",
  "GE",
  "NE",
  "BITWISEAND",
  "BITWISEOR",
  "ASSIGN",
  "NEW",
  "INSTANCEOF",
  "LEFTPARN",
  "RIGHTPARN",
  "LEFTBRACKET",
  "RIGHTBARCKET",
  "LEFTCURLY",
  "RIGHTCURLY",
  "COMMA",
  "DOT",
  "SEMICOLUMN",
  "FOR",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "NATIVE",
  "PACKAGE",
  "IMPORT",
  "CLASS",
  "INTERFACE",
  "ABSTRACT",
  "PUBLIC",
  "PROTECTED",
  "STATIC",
  "EXTENDS",
  "IMPLEMENTS",
  "SUPER",
  "FINAL"
  };
}

