
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NEW = 41;
  public static final int EXTENDS = 66;
  public static final int SHIFTLEFTOP = 36;
  public static final int LT = 28;
  public static final int RIGHTBARCKET = 45;
  public static final int SHIFTLEFT = 22;
  public static final int CLASS = 59;
  public static final int BINARYAND = 24;
  public static final int STATIC = 65;
  public static final int MINUS = 17;
  public static final int INTERFACE = 60;
  public static final int PACKAGE = 57;
  public static final int BYTE = 14;
  public static final int ELSE = 54;
  public static final int ID = 2;
  public static final int IF = 53;
  public static final int LEFTCURLY = 46;
  public static final int DOT = 49;
  public static final int FOR = 51;
  public static final int EQ = 27;
  public static final int BINARYOR = 25;
  public static final int STRINGLITERAL = 6;
  public static final int SEMICOLUMN = 50;
  public static final int NOT = 26;
  public static final int BITWISEOR = 34;
  public static final int NE = 32;
  public static final int PUBLIC = 62;
  public static final int PLUS = 16;
  public static final int INC = 38;
  public static final int NATIVE = 56;
  public static final int FLOATLITERAL = 4;
  public static final int CHAR = 13;
  public static final int error = 1;
  public static final int ASSIGN = 40;
  public static final int ABSTRACT = 61;
  public static final int INTGERLITERAL = 3;
  public static final int NULLLITERAL = 7;
  public static final int INT = 12;
  public static final int BITWISEAND = 33;
  public static final int RETURN = 55;
  public static final int IMPORT = 58;
  public static final int THISLITERAL = 8;
  public static final int FALSELITERAL = 10;
  public static final int CHARLITERAL = 5;
  public static final int RIGHTCURLY = 47;
  public static final int PROTECTED = 64;
  public static final int EOF = 0;
  public static final int BITWISEXOR = 35;
  public static final int GE = 31;
  public static final int COMMA = 48;
  public static final int SUPER = 68;
  public static final int MOD = 20;
  public static final int DEC = 39;
  public static final int TIMES = 18;
  public static final int LEFTBRACKET = 44;
  public static final int TRUELITERAL = 9;
  public static final int IMPLEMENTS = 67;
  public static final int SHIFTRIGHTOP = 37;
  public static final int LEFTPARN = 42;
  public static final int DIVIDES = 19;
  public static final int GT = 30;
  public static final int SHORT = 15;
  public static final int SHIFTRIGHT = 23;
  public static final int PRIVATE = 63;
  public static final int STAR = 21;
  public static final int RIGHTPARN = 43;
  public static final int BOOL = 11;
  public static final int LE = 29;
  public static final int WHILE = 52;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "INTGERLITERAL",
  "FLOATLITERAL",
  "CHARLITERAL",
  "STRINGLITERAL",
  "NULLLITERAL",
  "THISLITERAL",
  "TRUELITERAL",
  "FALSELITERAL",
  "BOOL",
  "INT",
  "CHAR",
  "BYTE",
  "SHORT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDES",
  "MOD",
  "STAR",
  "SHIFTLEFT",
  "SHIFTRIGHT",
  "BINARYAND",
  "BINARYOR",
  "NOT",
  "EQ",
  "LT",
  "LE",
  "GT",
  "GE",
  "NE",
  "BITWISEAND",
  "BITWISEOR",
  "BITWISEXOR",
  "SHIFTLEFTOP",
  "SHIFTRIGHTOP",
  "INC",
  "DEC",
  "ASSIGN",
  "NEW",
  "LEFTPARN",
  "RIGHTPARN",
  "LEFTBRACKET",
  "RIGHTBARCKET",
  "LEFTCURLY",
  "RIGHTCURLY",
  "COMMA",
  "DOT",
  "SEMICOLUMN",
  "FOR",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "NATIVE",
  "PACKAGE",
  "IMPORT",
  "CLASS",
  "INTERFACE",
  "ABSTRACT",
  "PUBLIC",
  "PRIVATE",
  "PROTECTED",
  "STATIC",
  "EXTENDS",
  "IMPLEMENTS",
  "SUPER"
  };
}

